### ISSUE TITLE
Return empty JSON if there are no results

### ISSUE THREAD

**Issue by r007** [ocius/api#2]
One of the issues with current API is its type inconsistency. Especially this line:
https://github.com/ocius/api/blob/128b8efca97189514c548155314c459468f81ff1/Endpoints/GetDrones/src/GetDrones/Models/DroneSensor.cs#L27

With an HTTP header ('Content-Type: application/json') you can't return a string. Because it won't be a valid JSON any more. It'll throw an error:

```
SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
```

Also, map function doesn't work for strings and the app crashes.

![App error](https://user-images.githubusercontent.com/78280/63817609-28c2d500-c94e-11e9-9b13-bbb4ff90835b.png)

Can you please:
1) Always return the JSON, no matter what.
2) If an error happened - simply return empty results ```{}```.

That's would be more than enough for me.

**Comment by thomasdane** [comment]
This is now complete. You can verify by visiting https://api.ocius.com.au/drones?timespan=foo
