### ISSUE TITLE
Fix DB queries: select by name instead of date

### ISSUE THREAD

**Issue by r007** [ocius/api#3]
API currently doesn't work as supposed to be. It either return two Bobs, either two Bruce, sometimes Bob+Bruce. And the reason for it is this:
https://github.com/ocius/api/blob/128b8efca97189514c548155314c459468f81ff1/Endpoints/GetDrones/src/GetDrones/Query.cs#L30
https://github.com/ocius/api/blob/128b8efca97189514c548155314c459468f81ff1/Endpoints/GetDrones/src/GetDrones/Query.cs#L15

Would be correctly to do something like this:
1) Set key condition expression to **name**.
2) Set sort key to **date**.
3) Limit output to only one **per name**.

So what we need is to select data by unique name, sort it by date and return only the latest record per item. A well crafted query could solve this problem. I'm not an expert in .NET/DynamoDB, can't help you here.

### Resources:
[Working with Queries in DynamoDB](https://docs.aws.amazon.com/en_us/amazondynamodb/latest/developerguide/Query.html)
[Querying | DynamoDB Explained](https://www.dynamodbguide.com/querying)

**Comment by thomasdane** [comment]
@r007 I have implemented your suggestion. The API will now only return Bob and Bruce. However, the origin is currently sending only Bruce and Crush. So it is showing only a single result. I will discuss with Lloyd.
