### ISSUE TITLE
Weird data coming from API

### ISSUE THREAD

**Issue by r007** [ocius/api#4]
Sometimes I'm receiving the following data from the API:

```json
[
{"Name":"Sarli","Timestamp":"1566966666","Status":"MAV_STATE_ACTIVE","Mode":"MANUAL","Sail_mode":null,"Props":{"Wp_dist":null,"Next_wp":null,"Water_depth":null,"Water_temp":null,"Water_speed":null,"Wind_Speed":null,"Wind_direction":null,"Boat_speed":null,"Throttle":null,"Num_Sats":null,"Hdop":null,"Heading":null,"Location":{"Coordinates":{"Lat":null,"Lon":null}}}},
{"Name":"Crush","Timestamp":"1566964865","Status":"MAV_STATE_ACTIVE","Mode":"MANUAL","Sail_mode":null,"Props":{"Wp_dist":null,"Next_wp":null,"Water_depth":null,"Water_temp":null,"Water_speed":null,"Wind_Speed":null,"Wind_direction":null,"Boat_speed":null,"Throttle":null,"Num_Sats":null,"Hdop":null,"Heading":null,"Location":{"Coordinates":{"Lat":null,"Lon":null}}}}
]
```

Basically two drones with names Crush and Sarli. With no location coordinates, all the properties are null. URL: https://api.ocius.com.au/drones

Please fix.

**Comment by thomasdane** [comment]
@r007 this is caused by the origin API returning that data. See https://dev.ocius.com.au/usvna/oc_server?listrobots&nodeflate

I can discuss with Lloyd and ask them to only send valid data.

**Comment by thomasdane** [comment]
@r007 I have implemented your suggestion. The API will now only return Bob and Bruce. However, if you the origin is currently sending only Bruce and Crush. So it is showing only a single result. I will discuss with Lloyd.
