### ISSUE TITLE
11AM edge case

### ISSUE THREAD

**Issue by Kevinwochan** [ocius/api#41]
happy hunting

**Comment by LorenzoLeeSolano** [comment]
@Kevinwochan
Can you describe to me where this edge case shows up, and what happens when it does? Can I find logs of it in cloudwatch?
I want to start looking into solving it :)

**Comment by Kevinwochan** [comment]
@LorenzoLeeSolano 
# Context: 
We have a lambda function running hourly that does basic checks on the API.
The project is here: https://github.com/ocius/apiTester (i'll add you to the mailing list for this)

# Issue:
Somedays at about 11AM i get an email from the API checker telling me that no cameras were found for our USVs. 
Here is the JSON response. (you might want to copy and paste it here https://jsonbeautify.com/)

```
 [{'Name': 'Bruce', 'Timestamp': '1610063999559', 'Status': 'MAV_STATE_ACTIVE', 'Props': {'Water_depth': '4.810000', 'Water_temp': '24.620001', 'Wind_speed': '1.380000', 'Wind_direction': '148.786514', 'Boat_speed': '0', 'Heading': '8', 'Batteries': ['28.3', '28.3'], 'BatteryPercentages': ['95', '93'], 'Cameras': [], 'Location': {'Coordinates': {'Lat': '-33.905965', 'Lon': '151.23496'}}}}, {'Name': 'Bob', 'Timestamp': '1610063999596', 'Status': 'MAV_STATE_ACTIVE', 'Props': {'Water_depth': '42949672', 'Water_temp': '35.060001', 'Wind_speed': '0.855310', 'Wind_direction': '302.113586', 'Boat_speed': '0.770000', 'Heading': '249', 'Batteries': ['28.5', '28.5', '28.4', '28.5'], 'BatteryPercentages': ['94', '95', '94', '94'], 'Cameras': [], 'Location': {'Coordinates': {'Lat': '-33.9060216', 'Lon': '151.2344383'}}}}, {'Name': 'Beth', 'Timestamp': '1610063999571', 'Status': 'MAV_STATE_STANDBY', 'Props': {'Water_depth': '9.800000', 'Water_temp': '0', 'Wind_speed': '2.425089', 'Wind_direction': '132.979141', 'Boat_speed': '0.660000', 'Heading': '69', 'Batteries': ['28.7', '28.6', '28.6', '28.7'], 'BatteryPercentages': ['99', '100', '99', '99'], 'Cameras': [], 'Location': {'Coordinates': {'Lat': '-33.9614', 'Lon': '151.1949816'}}}}]
```

# Theory:
What you'll notice if you copy and paste the timestamp `1610063999571`  into something more readable at https://www.epochconverter.com/ (copy and paste without the last 3 digits, we use a floating epoch timestamp)
![image](https://user-images.githubusercontent.com/18486383/105436385-38fdf180-5cb3-11eb-8514-ce1c95fddf68.png)


The time is `Thursday, January 7, 2021 11:59:59 PM GMT` . The ***theory*** is, is that when the day ticks over, the RawDataToClientData function is looking at the 8th of Jan for camera images but the most recent camera images are stored in the 7th of Jan. 

I've yet to actually test that theory against the code.

# Fix:
Implementation is up to you :D 
In terms of functionality, all we need is to ensure that if camera images are available then the public should be able to see them.

**Comment by LorenzoLeeSolano** [comment]
@Kevinwochan 
Thanks for the detailed description!
I can't seem to access https://github.com/ocius/apiTester. Is it a private repository?
I should be able to look into this without access though, so no stress.

**Comment by LorenzoLeeSolano** [comment]
No problems in the last 5 days!
Closing the issue.
