### ISSUE TITLE
Serve Weather Data: Conversions

### ISSUE THREAD

**Issue by LorenzoLeeSolano** [ocius/api#49]

**Comment by Kevinwochan** [comment]
we want everything in knots (nautilcal miles, everything larger than 0.5 knots)

**Comment by LorenzoLeeSolano** [comment]
Units for the weather data being served are as follows;

Wind_speed: metres per second,
Wind_direction: degrees TRUE(from north),
Current_speed: metres per second,
Current_direction: centi-degrees TRUE(degrees * 100).

I can make the appropriate conversions in the backend, but it might be better to make them in the frontend for consistency.

**Comment by LorenzoLeeSolano** [comment]
Conversions are being handled on the front end for now
